### ISSUE TITLE
Recipe issue

### ISSUE THREAD

**Issue by wild-defi** [gustawdaniel/bdl_web3#2]
There are the following issues with recipes 

1. Recipe instruction is missing on frontend, but exists in database.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/121158085/208857399-0228268d-a6ef-4f6d-adb4-4886e02bfe75.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/121158085/208857482-129c8e59-01fd-43d4-96c1-b51d36940eae.png">
2. short_description should not be required.
3. On the main page with all recipes. If the name of the recipe more than 2 line, hide the other lines with 3 dots. And all elements should be inside of the box 
<img width="279" alt="image" src="https://user-images.githubusercontent.com/121158085/208859118-b064ce96-cff7-4d18-aab8-7efd4e053165.png">
4. On the main page with all recipes. recipes should fit into screen width.

**Comment by gustawdaniel** [comment]
- [x] Recipe instruction is missing on frontend, but exists in database.
- [x] short_description should not be required. 
- [x] On the main page with all recipes. If the name of the recipe more than 2 line, hide the other lines with 3 dots. And all elements should be inside of the box
- [ ] On the main page with all recipes. recipes should fit into screen width.


@bakiworld can you add screenshots / design explaining last requirement?
